Various improvements

diff --git a/bin/setup-credentials b/bin/setup-credentials
--- a/bin/setup-credentials
+++ b/bin/setup-credentials
@@ -2,6 +2,17 @@
 
 source ./functions.sh
 
+echo "Validating sudo credentials for package installation, timedatectl access, and other privileged tasks!"
+sudo --validate
+if [[ $? != 0 ]]; then
+  echo "Could not validate sudo credentials!"
+  exit 255
+fi
+
+echo ""
+echo "Here. We. Go!"
+echo ""
+
 echo -n "Configuring GPG key... "
 
 if [ -d "$HOME/.gnupg" ]; then
@@ -26,6 +37,17 @@ if [ -f "$HOME/.ssh/id_ed25519" ]; then
   print_success_mark
   echo -e "\tExisting SSH key found, will not create new key!"
 else
-  ssh-keygen -t ed25519 -f "$HOME/.ssh/id_ed25519" -C "me@cspray.io"
-  print_success_mark
+  # Make sure we print a new line so we don't output next to the Configuring SSH Key
+  echo
+  echo -n "Please enter a password for your new SSH key: "
+  read -rs password
+  echo
+  echo -n "Confirm password for SSH key: "
+  read -rs confirm_password
+  if [[ $password == "$confirm_password" ]]; then
+    ssh-keygen -t ed25519 -f "$HOME/.ssh/id_ed25519" -C "me@cspray.io" -N "$password"
+    print_success_mark
+  else
+    print_failure_mark
+  fi
 fi
